@startuml

artifact Hardware {
  artifact Hypervisor {
    artifact Windows {
      artifact App_a
      artifact App_b
    }
    artifact Linux {
      artifact App_c
      artifact App_d
    }
  }
}

@enduml